# Auto-label PRs based on changed files
# Requires: actions/labeler@v5

new-skill:
  - changed-files:
      - any-glob-to-any-file: 'skills/*/SKILL.md'
    all:
      - head-branch: ['^(?!main$)']

skill-update:
  - changed-files:
      - any-glob-to-any-file:
          - 'skills/*/skill.ts'
          - 'skills/*/SKILL.md'

tooling:
  - changed-files:
      - any-glob-to-any-file:
          - 'dev/**'
          - '.github/**'

docs:
  - changed-files:
      - any-glob-to-any-file:
          - 'docs/**'
          - '*.md'
          - 'prompts/**'

examples:
  - changed-files:
      - any-glob-to-any-file: 'examples/**'
